#include "ros/ros.h"
#include "geometry_msgs/Quaternion.h"
#include "geometry_msgs/PoseStamped.h"
#include "styx_msgs/Lane.h"
#include "styx_msgs/Waypoint.h"
#include "nav_msgs/Path.h"
#include "Eigen/Core"
#include "Eigen/Dense"
#include "Eigen/Geometry"
#include <vector>
#include <fstream>
#include <iostream>
#include <sstream>
#include <math.h>
#include <pcl/
